[package]
name = "sessions-redis"
version = "0.1.2"
authors = ["FangDun Sai <cfddream@gmail.com>"]
description = "Sessions Redis Storage"
documentation = "https://docs.rs/sessions-redis"
homepage = "https://github.com/viz-rs/sessions"
license = "Apache-2.0/MIT"
readme = "README.md"
edition = "2018"

[features]
default = ["tokio-comp"]

tokio-comp = ["redis/tokio-comp"]
async-std-comp = ["redis/async-std-comp"]

[dependencies]
sessions-core = { path = "../sessions-core", version = "0.1.2" }

redis = { version = "0.19", features = ["aio"] }
serde_json = "1.0"
