[package]
name = "sessions-core"
version = "0.1.0"
authors = ["FangDun Sai <cfddream@gmail.com>"]
description = "Sessions Core"
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
serde = "1.0"
serde_json = "1.0"
