[package]
name = "sessions"
version = "0.0.2"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
repository = "https://github.com/trek-rs/sessions"
description = "General sessions module for web services"
documentation = "https://docs.rs/sessions"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1"
async-lock = "1.1"
async-trait = "0.1"
serde = "1"
serde_json = "1"
cookie = { version = "0.14", features = ["secure", "percent-encode"], optional = true }
blocking = { version = "0.5", optional = true }
nanoid = { version = "0.3", optional = true }
redis = { git = "https://github.com/mitsuhiko/redis-rs.git", branch = 'master', version = "0.17.1-alpha.0", default-features = false, features = ["tokio-comp", "async-std-comp"], optional = true }
# mongodb = { version = "0.9", optional = true }

[dev-dependencies]
http = "0.2"
futures = "0.3"
smol = "0.3"
tokio = { version = "0.2", features = ["rt-core", "rt-util", "rt-threaded", "test-util", "macros"] }
async-std = { version = "1.6", features = ["unstable", "attributes"] }
pretty_env_logger = "0.4"
time = "0.2"
log = "0.4"
tempfile = "3"

## warp
hyper = "0.13"
warp = "0.2"

## tide
tide = { version = "0.13", default-features = false, features = ["h1-server", "logger"] }

[features]
default = ["nanoid", "cookie"]
memory-store = []
fs-store = []
redis-store = ["redis"]

[[test]]
name = "memory"
required-features = ["memory-store", "blocking"]

[[test]]
name = "memory-warp-hyper"
required-features = ["memory-store"]

[[test]]
name = "fs-tokio"
required-features = ["fs-store", "blocking"]

[[test]]
name = "fs-async-std"
required-features = ["fs-store", "blocking"]

[[test]]
name = "redis-warp"
required-features = ["redis-store"]

[[test]]
name = "redis-tide"
required-features = ["redis-store"]
