[package]
name = "sessions"
version = "0.1.1"
authors = ["FangDun Sai <cfddream@gmail.com>"]
description = "General sessions module for web services"
documentation = "https://docs.rs/sessions"
homepage = "https://github.com/viz-rs/sessions"
license = "Apache-2.0/MIT"
readme = "README.md"
edition = "2018"

[features]
memory = ["sessions-memory"]
redis = ["sessions-redis"]

[dependencies]
sessions-core = { path = "../sessions-core", version = "0.1.1" }
sessions-memory = { path = "../sessions-memory", version = "0.1.0", optional = true }
sessions-redis = { path = "../sessions-redis", version = "0.1.0", optional = true }
