name: CI

on: [push, pull_request]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: memory
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test memory --features 'memory-store blocking'

      - name: memory-warp-hyper
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test memory-warp-hyper --features 'memory-store'

      - name: fs-tokio
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test fs-tokio --features 'fs-store blocking'

      - name: fs-async-std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test fs-async-std --no-default-features --features 'fs-store blocking'

      # - name: redis-warp
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --test redis-warp --features 'redis-store-tokio tokio'
      # - name: redis-tide
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --test redis-tide --no-default-features --features 'nanoid redis-store-async-std async-std cookie'

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      - name: fmt
        run: cargo fmt --all -- --check

      - name: Docs
        run: cargo doc
